-- ============================================================================
-- CLEVERLY - VECTOR SEARCH TEST SCRIPT
-- ============================================================================
-- This script tests the vector search functionality
-- Run this AFTER setting up the database with complete_setup.sql
-- ============================================================================

-- ============================================================================
-- PART 1: INSERT TEST DATA
-- ============================================================================

-- Create a test user profile
-- Note: In production, this would be created by Supabase Auth
INSERT INTO public.profiles (id, email, full_name)
VALUES (
  '00000000-0000-0000-0000-000000000001'::uuid,
  'test@cleverly.com',
  'Test User'
) ON CONFLICT (id) DO NOTHING;

-- Create a test course
INSERT INTO public.courses (id, user_id, title, description, topics)
VALUES (
  '00000000-0000-0000-0000-000000000002'::uuid,
  '00000000-0000-0000-0000-000000000001'::uuid,
  'Introduction to Machine Learning',
  'A comprehensive course covering ML fundamentals, supervised and unsupervised learning, neural networks, and practical applications.',
  ARRAY['machine learning', 'artificial intelligence', 'neural networks', 'supervised learning']
) ON CONFLICT (id) DO NOTHING;

-- Create a test course file
INSERT INTO public.course_files (id, course_id, file_name, file_type, file_path, status)
VALUES (
  '00000000-0000-0000-0000-000000000003'::uuid,
  '00000000-0000-0000-0000-000000000002'::uuid,
  'ml_fundamentals.pdf',
  'textbook',
  'test/ml_fundamentals.pdf',
  'embedded'
) ON CONFLICT (id) DO NOTHING;

-- Insert test embeddings with sample content
-- These use random vectors for demonstration
-- In production, embeddings would be generated by Google Gemini

INSERT INTO public.course_embeddings (course_file_id, content_chunk, embedding, metadata)
VALUES (
  '00000000-0000-0000-0000-000000000003'::uuid,
  'Machine learning is a subset of artificial intelligence that focuses on training algorithms to learn patterns from data. Unlike traditional programming where rules are explicitly coded, ML systems improve their performance through experience.',
  array_fill(0.0, ARRAY[768])::vector(768),
  '{"page": 1, "section": "Introduction"}'::jsonb
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.course_embeddings (course_file_id, content_chunk, embedding, metadata)
VALUES (
  '00000000-0000-0000-0000-000000000004'::uuid,
  'Supervised learning involves training models on labeled data. The algorithm learns to map inputs to outputs based on example input-output pairs. Common supervised learning tasks include classification and regression.',
  array_fill(0.1, ARRAY[768])::vector(768),
  '{"page": 5, "section": "Supervised Learning"}'::jsonb
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.course_embeddings (course_file_id, content_chunk, embedding, metadata)
VALUES (
  '00000000-0000-0000-0000-000000000005'::uuid,
  'Neural networks are computing systems inspired by biological neural networks. They consist of interconnected nodes (neurons) organized in layers. Deep learning uses neural networks with multiple hidden layers to learn hierarchical representations.',
  array_fill(0.2, ARRAY[768])::vector(768),
  '{"page": 12, "section": "Neural Networks"}'::jsonb
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.course_embeddings (course_file_id, content_chunk, embedding, metadata)
VALUES (
  '00000000-0000-0000-0000-000000000006'::uuid,
  'Unsupervised learning works with unlabeled data to discover hidden patterns or structures. Common techniques include clustering, dimensionality reduction, and anomaly detection. K-means and hierarchical clustering are popular clustering algorithms.',
  array_fill(0.15, ARRAY[768])::vector(768),
  '{"page": 8, "section": "Unsupervised Learning"}'::jsonb
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.course_embeddings (course_file_id, content_chunk, embedding, metadata)
VALUES (
  '00000000-0000-0000-0000-000000000007'::uuid,
  'Model evaluation is crucial in machine learning. Common metrics include accuracy, precision, recall, and F1-score for classification tasks. For regression, we use metrics like mean squared error (MSE) and R-squared. Cross-validation helps assess model generalization.',
  array_fill(0.25, ARRAY[768])::vector(768),
  '{"page": 18, "section": "Model Evaluation"}'::jsonb
) ON CONFLICT (id) DO NOTHING;

SELECT 'Test data inserted successfully!' as status;

-- ============================================================================
-- PART 2: TEST VECTOR SEARCH FUNCTION
-- ============================================================================

-- Test 1: Basic search - find top 3 most similar chunks
SELECT
  '--- Test 1: Basic Vector Search (Top 3) ---' as test_name;

SELECT
  id,
  LEFT(content_chunk, 100) || '...' as content_preview,
  similarity,
  metadata
FROM match_course_embeddings(
  array_fill(0.0, ARRAY[768])::vector(768),
  '00000000-0000-0000-0000-000000000002'::uuid,
  3
);

-- Test 2: Find all matching chunks (up to 5)
SELECT
  '--- Test 2: Find Top 5 Matches ---' as test_name;

SELECT
  id,
  LEFT(content_chunk, 80) || '...' as content_preview,
  similarity,
  (metadata->>'page')::int as page_number,
  metadata->>'section' as section
FROM match_course_embeddings(
  array_fill(0.1, ARRAY[768])::vector(768),
  '00000000-0000-0000-0000-000000000002'::uuid,
  5
)
ORDER BY similarity DESC;

-- Test 3: Different query vector
SELECT
  '--- Test 3: Different Query Vector ---' as test_name;

SELECT
  id,
  LEFT(content_chunk, 80) || '...' as content_preview,
  similarity,
  metadata->>'section' as section
FROM match_course_embeddings(
  array_fill(0.2, ARRAY[768])::vector(768),
  '00000000-0000-0000-0000-000000000002'::uuid,
  3
)
ORDER BY similarity DESC;

-- ============================================================================
-- PART 3: VERIFY DATA INTEGRITY
-- ============================================================================

SELECT '--- Data Integrity Check ---' as test_name;

-- Count embeddings per course file
SELECT
  cf.file_name,
  COUNT(ce.id) as embedding_count,
  AVG(CHAR_LENGTH(ce.content_chunk)) as avg_chunk_length
FROM public.course_files cf
LEFT JOIN public.course_embeddings ce ON cf.id = ce.course_file_id
WHERE cf.course_id = '00000000-0000-0000-0000-000000000002'::uuid
GROUP BY cf.file_name;

-- Check embedding dimensions
SELECT
  id,
  vector_dims(embedding) as dimensions,
  LEFT(content_chunk, 50) || '...' as content_preview
FROM public.course_embeddings
WHERE course_file_id = '00000000-0000-0000-0000-000000000003'::uuid
LIMIT 5;

-- ============================================================================
-- PART 4: PERFORMANCE TEST
-- ============================================================================

SELECT '--- Performance Test ---' as test_name;

-- Time the vector search query
EXPLAIN ANALYZE
SELECT
  ce.id,
  ce.content_chunk,
  1 - (ce.embedding <=> array_fill(0.0, ARRAY[768])::vector(768)) as similarity
FROM public.course_embeddings ce
JOIN public.course_files cf ON ce.course_file_id = cf.id
WHERE cf.course_id = '00000000-0000-0000-0000-000000000002'::uuid
ORDER BY ce.embedding <=> array_fill(0.0, ARRAY[768])::vector(768)
LIMIT 5;

-- ============================================================================
-- PART 5: CLEANUP (OPTIONAL)
-- ============================================================================

-- Uncomment the following to clean up test data after testing

-- DELETE FROM public.profiles WHERE id = '00000000-0000-0000-0000-000000000001'::uuid;
-- This will cascade delete:
-- - The test course
-- - The test course file
-- - All test embeddings

-- SELECT 'Test data cleaned up!' as status;

-- ============================================================================
-- TEST COMPLETE!
-- ============================================================================
-- If all tests ran successfully, your vector search is working correctly!
-- ============================================================================

SELECT '=== ALL TESTS COMPLETE ===' as final_status;
